/**
 * communes-dz.js — Communes officielles algériennes par wilaya
 * Source : découpage administratif DZ officiel (daïras + chefs-lieux)
 * Utilisé par : /api/admin/sync-communes (enrichissement ZR)
 *
 * Format : { wilaya_code: ["commune1", "commune2", ...] }
 * ~900+ communes couvrant les 58 wilayas
 */

export const COMMUNES_DZ = {
  1: ["Adrar","Aougrout","Fenoughil","Timimoun","Reggane","In Zghmir","Tsabit","Aoulef","Charouine","Bordj Badji Mokhtar"],
  2: ["Chlef","Ténès","Ain Merane","Taougrite","El Karimia","Zeboudja","Benairia","Ouled Farès","Oued Fodda","Breira","Bir Halouane","Labiod Medjadja","Sendjas","Harchoun","Chettia","Oued Sly","Abou El Hassan"],
  3: ["Laghouat","Aflou","Ain Madhi","El Ghicha","Gueltat Sidi Saad","Sidi Makhlouf","El Haouaita","Hassi Delaa","Sebgag","Oued Morra","El Assafia","El Houaita"],
  4: ["Ain M'lila","Oum El Bouaghi","Ain Beida","Ain Fakroun","Sigus","Ain Kercha","Meskiana","El Amiria","Zorg","Souk Naamane","Berriche","Fkirina","Ouled Gacem","Hanchir Toumghani"],
  5: ["Batna","Ain Touta","Arris","Barika","Biskra","N'Gaous","Merouana","Seriana","Tazoult","Chemora","Ain Djasser","El Madher","Oued El Ma","Ghassira","Ichmoul","Timgad","Ras El Aioun","Hidoussa","Lemsane"],
  6: ["Béjaïa","Akbou","El Kseur","Amizour","Sidi Aich","Tichy","Taskriout","Kherrata","Darguina","Ighram","Oued Ghir","Aokas","Beni Maouche","Chemini","Souk El Tenine","Tazmalt","Adekar","Bejaia","Seddouk"],
  7: ["Biskra","Tolga","Sidi Okba","El Kantara","Ouled Djellal","Zeribet El Oued","Oumache","M'Chouneche","Djemorah","Ain Naga","Ras El Miad","El Hadjeb","Foughala","Lichana","Besbes"],
  8: ["Béchar","Kenadsa","Beni Abbès","Abadla","Tabalbala","Taghit","El Bnoud","Lahmar","Boukais","Igli"],
  9: ["Blida","Boufarik","Meftah","El Affroun","Larbaâ","Beni Tamou","Bouinan","Chebli","Oued El Alleug","Bou Arfa","Soumaa","El Afroun","Guerrouaou","Chrea","Ben Khelil","Mouzaïa","Ain Romana","Bougara","Hammam Melouane","Oued Djer","Djebabra","Fontaine Saadane"],
  10: ["Bouira","Ain Bessem","Sour El Ghozlane","Lakhdaria","Bechloul","El Hakimia","Hadjera Zerga","Chorfa","Aomar","El Adjiba","Zbarbar","Saharidj","Kadiria","Ain El Hadjar","Raouraoua"],
  11: ["Tamanrasset","In Guezzam","In Salah","Tazrouk","Abalessa","Ideles"],
  12: ["Tébessa","Bir El Ater","Cheria","Ain Zerga","El Ogla","Ouenza","Bekkaria","Hammamet","El Houidjbet","El Ogla El Malha","Boukhadra","Thlidjene","Morsott"],
  13: ["Tlemcen","Maghnia","Nedroma","Ghazaouet","Remchi","Sidi Bel Abbes","El Fehoul","Mansourah","Sidi Djilali","Ain Tallout","Beni Snous","Bab El Assa","Ouled Mimoun","Sidi Abdelli","Honaine","Sebdou","Beni Bahdel","Ain Fezza","Ouled Riyah"],
  14: ["Tiaret","Sougueur","Ksar Chellala","Mehdia","Ain Deheb","Oued Lilli","Madna","Zmalet El Emir Abdelkader","Rechaiga","Rahouia","Ain El Hadid","Mechraa Safa","Sidi Bakhti","Guertoufa","Dahmouni"],
  15: ["Tizi Ouzou","Azazga","Ain El Hammam","Bouzeguene","Maatkas","Ouaguenoun","Boghni","Draa Ben Khedda","Draa El Mizan","Azeffoun","Tigzirt","Mekla","Makouda","Beni Douala","Ath Zmenzer","Larbaa Nait Irathen","Frikat","Iferhounene","Ouacifs","Illilten"],
  16: ["Alger Centre","Bab El Oued","Hussein Dey","Kouba","El Harrach","Bouzareah","Bir Mourad Raïs","El Biar","Hydra","Birtouta","Baba Hassen","Dar El Beïda","Birkhadem","Beni Messous","Sidi M'hamed","El Madania","Belcourt","El Mouradia","Didouche Mourad","Rouïba","Reghaia","Ain Taya","Bordj El Kiffan","Bourouba","El Marsa","Tessala El Merdja","Saoula","Ain Benian","Cheraga","Ouled Fayet","Dely Ibrahim","El Achour","Gué de Constantine","Mohammadia","Bachdjerrah","Ben Aknoun","El Hammamet","Heuraoua","Khraicia","Les Eucalyptus","Mahelma","Rahmania","Sebbala","Sidi Abdallah","Souidania","Douera","Draria"],
  17: ["Djelfa","Ain Oussera","Messaad","El Idrissia","Hassi Bahbah","Birine","Charef","Sed Rahal","El Khemis","Ain Chouhada","Aïn Feka","Oum Laadham","Bouira Lahdab","Dar Chioukh"],
  18: ["Jijel","El Milia","Taher","Ziama Mansouriah","Settara","Texenna","El Aouana","Sidi Maarouf","Boudria Beni Yadjis","Selma Benziada","Chekfa","El Ancer","Ghebala","Kaous","Ouled Yahia Khedrouche"],
  19: ["Sétif","El Eulma","Ain El Kebira","Aïn Arnat","Bazer Sakhra","Ain Oulmane","El Ouricia","Hammam Guergour","Beidha Bordj","Ain Azel","Bir El Arch","Bouandas","Dehamcha","Djemila","El Melanis","El Ouldja","Guenzet","Guidjel","Hamma","Maoklane","Mezloug","Oum El Djallil","Rasfa","Salah Bey","Taouriret"],
  20: ["Saïda","Ain El Hadjar","Ouled Brahim","Sidi Ahmed","Doui Thabet","Youb","Ain Sekhouna","Moulay Larbi","Ain Sultan","El Hassasna","Tircine"],
  21: ["Skikda","Azzaba","El Harrouch","Collo","Tamalous","Ain Kechra","Fil Fila","Oum Toub","Ramdane Djamel","Cheraia","Hamadi Krouma","Ben Aziz","Salah Bouchaour","Ain Zouit"],
  22: ["Sidi Bel Abbès","Telagh","Sfisef","Ain El Berd","Ben Badis","Mostefa Ben Brahim","Moulay Slissen","Telelat","Ain Thrid","Badredine El Mokrani","Bir El Hammam","Lamtar","Marhoum","Merine","Mezaourou","Sidi Chaib","Tessala","Tilmouni","Ras El Ma"],
  23: ["Annaba","El Bouni","El Hadjar","Ain El Berd","Berrahal","Chetaïbi","Seraïdi","Treat","Eulma","Ain Berda","Chorfa"],
  24: ["Guelma","Bouchegouf","Hammam Debagh","Heliopolis","Ain Ben Beida","Ain Makhlouf","Ain Sandel","Bordj Sabath","El Fedjoudj","Khezaras","Medjez Amar","Medjez Sfa","Nechmaya","Sellaoua Announa","Tamlouka"],
  25: ["Constantine","El Khroub","Ain Smara","Hamma Bouziane","Didouche Mourad","Ain Abid","Beni Hmidane","Ibn Badis","Ouled Rahmoun","Messaoud Boudjeriou","Zighoud Youcef"],
  26: ["Médéa","Ksar El Boukhari","Berrouaghia","Ain Boucif","El Omaria","Ain El Ain","Aziz","Bir Ben Laabed","Bouskene","Chelalet El Adaoura","Chellalet El Adaoura","Derrag","El Hamdania","El Kerma","Hadjout","Mihoub","Oued Harbil","Ouled Antar","Ouzera","Saneg","Si Mahdjoub","Sidi Damed","Sidi Naamane","Sidi Ziane","Souagui","Tablat","Tafraout","Tizi Mahdi","Deux Bassins"],
  27: ["Mostaganem","Ain Nouissy","Ain Tedeles","Mazagran","Achaacha","Bouguirat","Hassi Mameche","Kheir Eddine","Mansourah","Mesra","Nekmaria","Ouled Maalah","Stidia","Touahria","Wadi El Abtal"],
  28: ["M'Sila","Boussaâda","Ain El Melh","Hammam Dalaa","Magra","Sidi Aissa","Ain El Hadjel","Ain Fares","Ben Srour","Bou Saada","Bousaada","Debbab","Djebel Messaad","El Hamel","Sidi Ameur","Tarmount","Tassameurt","Wanougha","Zarzour"],
  29: ["Mascara","Tighennif","Sig","Ain Fekan","Botima","Ghriss","Hacine","Khalouia","Makdha","Matemore","Mohammadia","Nesmoth","Oggaz","Oued El Abtal","Sedjerara","Tizi","Zahana"],
  30: ["Ouargla","Hassi Messaoud","Ain Beida","El Hadjira","El Borma","Nezla","Sidi Khouiled","Tebesbest","Touggourt","N'Goussa","Rouissat","Sidi Slimane"],
  31: ["Oran","Bir El Djir","Es Sénia","Sidi Chahmi","Arzew","Ain El Turck","El Kerma","Ain El Bia","Bir Ghbalou","Boufatis","Boutlelis","El Ancor","El Braya","Gdyel","Hassi Ben Okba","Hassi Bounif","Marsa El Hadjadj","Mers El Hadjadj","Oued Tlelat","Sidi Ben Youb"],
  32: ["El Bayadh","Brezina","Rogassa","El Abiodh Sidi Cheikh","Labiodh Sidi Cheikh","Boualem","Chellala","El Bnoud","Sidi Ameur","Stitten"],
  33: ["Illizi","In Amenas","Djanet","Bordj El Houass","In Guezzam"],
  34: ["Bordj Bou Arréridj","Bordj Ghedir","Bordj Zemoura","El Main","Ghilassa","Khelil","Mansoura","Medjana","Ouled Brahem","Ouled Dahmane","Ras El Oued","Ras El Oued","Tassameurt","Tixter","Teniet En Nasr"],
  35: ["Boumerdès","Bordj Menaïel","Naciria","Dellys","Khemis El Khechna","Boudouaou","Corso","Benchaabane","Boumerdes","Chabet El Ameur","El Kharrouba","Isser","Larbatache","Ouled Aissa","Si Mustapha","Souk El Had","Zeghara","Zemmouri"],
  36: ["El Tarf","Ben Mhidi","El Kala","Ain El Assel","Bessbes","Bouteldja","Chihani","Drean","Hammam Beni Salah","Raml Souk","Zerizer"],
  37: ["Tindouf","Oum El Assel","Tindouf"],
  38: ["Tissemsilt","Theniet El Had","Bordj Bou Naama","Bordj El Emir Abdelkader","Ammari","Beni Lahcene","Sidi Abed","Sidi Boutouchent","Lazharia","Larbaa"],
  39: ["El Oued","Robbah","Reguiba","Guemar","Bayadha","El Mghair","Kouinine","Nakhla","Oum Touyour","Sidi Aoun","Still","Trifaoui"],
  40: ["Khenchela","Baghai","Babar","Chechar","El Hamma","Ensigha","Kais","Khirane","M'Sara","Ouled Rechache","Tamza","Taouziant"],
  41: ["Souk Ahras","Sedrata","Taoura","Ain Soltane","Bir Bouhouche","Drea","Hannache","Heddada","Khedara","Machroha","Merahna","Oum El Adhaim","Ouillen","Zaarouria"],
  42: ["Tipaza","Cherchell","Hadjout","Bou Ismail","Ain Tagourait","Attatba","Bourkika","Chaïba","Damous","El Affroun","Fouka","Gouraya","Koléa","Larhat","Mahelma","Menaceur","Messelmoun","Nador","Oued El Alleug","Sidi Ghiles","Sidi Semiane","Zeralda"],
  43: ["Mila","Chelghoum Laid","Ain Tine","Ain Mellouk","Eleulaïa","Ferdjioua","Grarem Gouga","Oued Endja","Sidi Khelifa","Tadjenanet","Tassadane Haddada","Teleghma","Terrai Bainen","Yahia Beni Guecha"],
  44: ["Aïn Defla","Khemis Miliana","El Abadia","Ain Torki","Ain Lechiakh","Ain Lechikh","Attaf","Bir Ould Khelifa","Bordj Emir Khaled","Bourached","Boumedfaa","Djemaa Ouled Cheikh","El Amra","El Attaf","El Maine","Hoceinia","Mekhatria","Miliana","Oued Chorfa","Oued Fodda","Rouina","Sidi Lakhdar"],
  45: ["Naâma","Ain Ben Khelil","Mecheria","Aïn Sefra","Sfissifa","Tiout","Mekmen Ben Amar","Djeniene Bourezg","El Biod","Kasdir"],
  46: ["Aïn Témouchent","El Malah","Ain El Arba","Ain Kihal","Ain Tolba","Aghlal","Beni Saf","Chentouf","El Amria","Hammam Bou Hadjar","Hassasna","Messai","Oulhaça El Gheraba","Ouled Kihal","Sidi Ben Adda","Sidi Boumediene","Sidi Safi"],
  47: ["Ghardaïa","Berriane","El Guerrara","Metlili","Bounoura","Zelfana","El Atteuf","Daia Ben Dahoua","Sebseb","Mansoura"],
  48: ["Relizane","Oued Rhiou","Zemmoura","Ain Tarek","Ammi Moussa","El Hamadna","El Matmar","Hadj Mechri","Kalaa","Lahlef","Mazouna","Mendes","Ouarizane","Sidi Khettab","Sidi M'hamed Benaouda","Yellel"],
  49: ["Timimoun","Ouled Said","Aougrout","Charouine","Deldoul","In Zghmir","Metarfa","Ouled Aissa","Tabelkoza"],
  50: ["Bordj Badji Mokhtar","Timiaouine","Bordj Badji Mokhtar"],
  51: ["Ouled Djellal","Doucen","Ras El Miad","Sidi Khaled"],
  52: ["Béni Abbès","Beni Abbes","Ksabi","Ouled Khoudir","Tamtert"],
  53: ["In Salah","Foggaret Ezzaouia","In Ghar","In Salah"],
  54: ["In Guezzam","Bordj El Khadra","In Guezzam","Tarat"],
  55: ["Touggourt","Megarine","Nezla","Taibet","Temacine","Zaouia El Abidia","Benaceur","El Hadjira"],
  56: ["Djanet","Bordj El Houass","Djanet","Illizi"],
  57: ["El M'Ghair","Djamaâ","El M'Ghair","Oued El Alenda","Sidi Amrane","Still"],
  58: ["El Meniaa","Beriane","El Meniaa","Hassi Gara"],
};

export const WILAYAS_DZ_INFO = [
  [1,"Adrar"],[2,"Chlef"],[3,"Laghouat"],[4,"Oum El Bouaghi"],[5,"Batna"],
  [6,"Béjaïa"],[7,"Biskra"],[8,"Béchar"],[9,"Blida"],[10,"Bouira"],
  [11,"Tamanrasset"],[12,"Tébessa"],[13,"Tlemcen"],[14,"Tiaret"],[15,"Tizi Ouzou"],
  [16,"Alger"],[17,"Djelfa"],[18,"Jijel"],[19,"Sétif"],[20,"Saïda"],
  [21,"Skikda"],[22,"Sidi Bel Abbès"],[23,"Annaba"],[24,"Guelma"],[25,"Constantine"],
  [26,"Médéa"],[27,"Mostaganem"],[28,"M'Sila"],[29,"Mascara"],[30,"Ouargla"],
  [31,"Oran"],[32,"El Bayadh"],[33,"Illizi"],[34,"Bordj Bou Arréridj"],[35,"Boumerdès"],
  [36,"El Tarf"],[37,"Tindouf"],[38,"Tissemsilt"],[39,"El Oued"],[40,"Khenchela"],
  [41,"Souk Ahras"],[42,"Tipaza"],[43,"Mila"],[44,"Aïn Defla"],[45,"Naâma"],
  [46,"Aïn Témouchent"],[47,"Ghardaïa"],[48,"Relizane"],[49,"Timimoun"],[50,"Bordj Badji Mokhtar"],
  [51,"Ouled Djellal"],[52,"Béni Abbès"],[53,"In Salah"],[54,"In Guezzam"],[55,"Touggourt"],
  [56,"Djanet"],[57,"El M'Ghair"],[58,"El Meniaa"],
];
